name: Frictionless Data
organisation: Open Knowledge International
ga_code: UA-8271754-41
specifications:
  -
    slug: tableschema
    name: Table Schema
  -
    slug: dataresource
    name: Data Resource
  -
    slug: tabular-dataresource
    name: Tabular Data Resource
  -
    slug: datapackage
    name: Data Package
  -
    slug: tabular-datapackage
    name: Tabular Data Package
  -
    slug: fiscal-datapackage
    name: Fiscal Data Package
  -
    slug: datapackage-identifier
    name: Data Package Identifier
  -
    slug: csvdialect
    name: CSV Dialect
menu:
  -
    location: "http://frictionlessdata.io/"
    name: Main Site
  -
    location: "https://discuss.okfn.org/c/frictionless-data"
    name: Discussion Forum
  -
    location: "https://gitter.im/frictionlessdata/chat"
    name: Chat Channel
  -
    location: "https://github.com/frictionlessdata/specs/issues"
    name: Issue Tracker
  -
    location: "https://twitter.com/OKFNLabs"
    name: Twitter
highlighter: rouge
gems:
  - jekyll-redirect-from
markdown: kramdown
baseurl:
defaults:
  -
    scope:
      path: ""
    values:
      layout: "spec"
  -
    scope:
      path: "reference"
    values:
      reference: true
