name: Frictionless Data
highlighter: rouge
gems:
  - jekyll-redirect-from
markdown: kramdown
baseurl: 
defaults:
  -
    scope:
      path: ""
    values:
      layout: "spec"
  -
    scope:
      path: "reference"
    values:
      reference: true
