---
dataPackage:
  title: Data Package
  description: Data Package
  type: object
  required:
  - resources
  properties:
    profile:
      "$ref": "#/definitions/profile"
      propertyOrder: 10
    name:
      "$ref": "#/definitions/name"
      propertyOrder: 10
    id:
      "$ref": "#/definitions/id"
      propertyOrder: 20
    title:
      "$ref": "#/definitions/title"
      propertyOrder: 20
    description:
      "$ref": "#/definitions/description"
      propertyOrder: 30
      format: textarea
    homepage:
      "$ref": "#/definitions/homepage"
      propertyOrder: 40
    resources:
      "$ref": "#/definitions/dataResources"
      propertyOrder: 50
      options:
        hidden: true
    sources:
      "$ref": "#/definitions/sources"
      propertyOrder: 140
      options:
        hidden: true
    licenses:
      "$ref": "#/definitions/licenses"
      description: The license(s) under which the resource is published.
      propertyOrder: 150
      options:
        hidden: true
tabularDataPackage:
  title: Tabular Data Package
  description: Tabular Data Package
  type: object
  required:
  - resources
  - profile
  properties:
    profile:
      "$ref": "#/definitions/profile"
      propertyOrder: 10
    name:
      "$ref": "#/definitions/id"
      propertyOrder: 20
    title:
      "$ref": "#/definitions/title"
      propertyOrder: 20
    description:
      "$ref": "#/definitions/description"
      propertyOrder: 30
      format: textarea
    homepage:
      "$ref": "#/definitions/homepage"
      propertyOrder: 40
    resources:
      "$ref": "#/definitions/tabularDataResources"
      propertyOrder: 50
      options:
        hidden: true
    sources:
      "$ref": "#/definitions/sources"
      propertyOrder: 140
      options:
        hidden: true
    licenses:
      "$ref": "#/definitions/licenses"
      description: The license(s) under which the resource is published.
      propertyOrder: 150
      options:
        hidden: true
dataResources:
  title: Data Resources
  description: An `array` of Data Resource objects, each compliant with the [Data Resource](/data-resource/) specification.
  type: array
  minItems: 1
  items:
    "$ref": "#/definitions/dataResource"
  examples:
  - |
      {
        "resources": [
          {
            "name": "my-data",
            "data": [
              "data.csv"
            ],
            "mediatype": "text/csv"
          }
        ]
      }
tabularDataResources:
  title: Tabular Data Resources
  description: An `array` of Tabular Data Resource objects, each compliant with the [Tabular Data Resource](/tabular-data-resource/) specification.
  type: array
  minItems: 1
  items:
    "$ref": "#/definitions/tabularDataResource"
  examples:
  - |
      {
        "resources": [
          {
            "name": "my-data",
            "data": [
              "data.csv"
            ],
            "schema": "tableschema.json",
            "mediatype": "text/csv"
          }
        ]
      }
